import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateClinicalPDF = (historyData, patientProfile) => {
  const doc = jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // 1. Branding & Header
  doc.setFillColor(28, 43, 58); // Navy
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('HEALTH COMPASS', 20, 25);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Clinical Cognitive Assessment Report', 20, 32);

  // 2. Patient Profile Section
  doc.setTextColor(28, 43, 58);
  doc.setFontSize(16);
  doc.text('Patient Profile', 20, 55);

  doc.setFontSize(10);
  autoTable(doc, {
    startY: 60,
    head: [['Field', 'Information']],
    body: [
      ['Name', patientProfile.name || 'N/A'],
      ['Age', patientProfile.age || 'N/A'],
      ['Education', patientProfile.education || 'N/A'],
      ['Occupation', patientProfile.occupation || 'N/A'],
      ['Assessment Cycle', `${historyData.length} sessions recorded`]
    ],
    theme: 'striped',
    headStyles: { fillColor: [74, 124, 111] } // Sage
  });

  // 3. Longitudinal Data Table
  doc.setFontSize(16);
  doc.text('Assessment History', 20, doc.lastAutoTable.finalY + 15);

  const tableData = historyData.map(entry => {
    // 1. Safe extraction of interpretation level
    const interp = typeof entry.interpretation === 'string'
      ? entry.interpretation
      : (entry.interpretation?.level || entry.interpretation?.summary || 'No summary');

    // 2. Safe extraction of adjusted MoCA score
    const mocaScore = entry.scores?.mocaEquivalent?.adjusted ?? entry.scores?.mocaEquivalent ?? 0;

    return [
      new Date(entry.createdAt).toLocaleDateString(),
      `${mocaScore}/30`,
      `${Math.round((entry.scores?.raw?.earned || 0) / (entry.scores?.raw?.total || 1) * 100)}%`,
      entry.prediction || (mocaScore >= 26 ? 'Stable' : 'Observation'),
      interp.substring(0, 50) + '...'
    ];
  });

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [['Date', 'MoCA Eq.', 'Accuracy', 'Risk Status', 'Interpretation Summary']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [28, 43, 58] }
  });

  // 4. Detailed Clinical Notes
  if (historyData.length > 0) {
    const latest = historyData[0];
    doc.addPage();
    doc.setFontSize(16);
    doc.text('Latest Assessment Details', 20, 25);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Interpretation:', 20, 40);
    doc.setFont('helvetica', 'normal');

    const interpretationText = typeof latest.interpretation === 'string'
      ? latest.interpretation
      : (latest.interpretation?.level || 'No level provided.');

    const splitText = doc.splitTextToSize(interpretationText, pageWidth - 40);
    doc.text(splitText, 20, 48);

    doc.setFont('helvetica', 'bold');
    doc.text('Risk Prediction:', 20, doc.lastAutoTable ? doc.lastAutoTable.finalY + 40 : 80);
    doc.setFont('helvetica', 'normal');
    doc.text(latest.prediction || 'Pending analysis.', 20, doc.lastAutoTable ? doc.lastAutoTable.finalY + 48 : 88);
  }

  // 5. Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by HealthCompass Clinical System - ${new Date().toLocaleString()} - Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  }

  doc.save(`HealthCompass_Report_${patientProfile.name || 'Patient'}.pdf`);
};
